"""URL routes for the lightweight project dashboard."""

from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = "ciudades_del_mundo"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("api/countries/", views.api_country_summary, name="api_country_summary"),
    path("api/countries/<slug:country_code>/", views.api_country_detail, name="api_country_detail"),
    path("api/admin-areas/<path:area_id>/", views.api_admin_area_detail, name="api_admin_area_detail"),
    path("api/new-country-containers/", views.api_new_country_summary, name="api_new_country_summary"),
    path(
        "api/new-country-containers/<slug:country_slug>/config-tree/",
        views.api_new_country_config_tree,
        name="api_new_country_config_tree",
    ),
    path(
        "api/new-country-containers/<slug:country_slug>/config-nodes/<path:tree_id>/",
        views.api_new_country_config_node_detail,
        name="api_new_country_config_node_detail",
    ),
    path(
        "api/new-country-containers/<slug:country_slug>/",
        views.api_new_country_container_detail,
        name="api_new_country_container_detail",
    ),
    path("api/new-countries/<slug:country_id>/", views.api_new_country_detail, name="api_new_country_detail"),
    path("api/new-areas/<path:area_id>/", views.api_new_area_detail, name="api_new_area_detail"),
    path("api/derived/", views.api_derived_summary, name="api_derived_summary"),
    path("api/tasks/", views.api_task_list, name="api_task_list"),
    path("api/tasks/<slug:task_id>/", views.api_task_detail, name="api_task_detail"),
    path("api/assets/<slug:entity_type>/<path:entity_key>/", views.api_visual_assets, name="api_visual_assets"),
    path("dashboard/population/", views.dashboard_population_data, name="dashboard_population_data"),
    path("dashboard/derived/", views.dashboard_derived_data, name="dashboard_derived_data"),
    path("dashboard/country/<slug:country_code>/", views.dashboard_country_detail, name="dashboard_country_detail"),
    path("areas/", views.admin_area_list, name="admin_area_list"),
    path("areas/table/", views.admin_area_table, name="admin_area_table"),
    path("configs/", views.config_list, name="config_list"),
    path("configs/table/", views.config_table, name="config_table"),
    path("configs/bootstrap/", views.config_bootstrap, name="config_bootstrap"),
    path("configs/import-toml/", views.config_import_toml, name="config_import_toml"),
    path("configs/tasks/table/", views.config_tasks_table, name="config_tasks_table"),
    path("configs/new/", views.config_new, name="config_new"),
    path("configs/all/task/<slug:action>/", views.start_all_config_task, name="start_all_config_task"),
    path("configs/<slug:slug>/export-toml/", views.config_export_toml, name="config_export_toml"),
    path("configs/<slug:slug>/import-toml/", views.config_import_toml_slug, name="config_import_toml_slug"),
    path("configs/<slug:slug>/cities/export-toml/", views.config_city_merge_export_toml, name="config_city_merge_export_toml"),
    path("configs/<slug:slug>/cities/import-toml/", views.config_city_merge_import_toml, name="config_city_merge_import_toml"),
    path("configs/<slug:slug>/export-data-csv/", views.config_export_data_csv, name="config_export_data_csv"),
    path("configs/<slug:slug>/editor-data/", views.config_editor_data, name="config_editor_data"),
    path("configs/<slug:slug>/", views.config_edit, name="config_edit"),
    path("configs/<slug:slug>/summary/", views.config_summary, name="config_summary"),
    path("configs/<slug:slug>/source-entities/", views.config_source_entities, name="config_source_entities"),
    path("configs/<slug:slug>/generate/", views.config_generate_base, name="config_generate_base"),
    path("configs/<slug:slug>/ai-login/", views.config_ai_login, name="config_ai_login"),
    path("configs/<slug:slug>/task/<slug:action>/", views.start_config_task, name="start_config_task"),
    path("recipes/", views.recipe_list, name="recipe_list"),
    path("recipes/new/", views.recipe_new, name="recipe_new"),
    path("recipes/<slug:slug>/", views.recipe_edit, name="recipe_edit"),
    path("recipes/<slug:slug>/task/<slug:action>/", views.start_recipe_task, name="start_recipe_task"),
    path("new-countries/", views.new_country_list, name="new_country_list"),
    path("new-countries/import-toml/", views.new_country_import_toml, name="new_country_import_toml"),
    path(
        "new-countries/source-children/",
        views.new_country_source_children,
        name="new_country_source_children",
    ),
    path("new-countries/new/", views.new_country_new, name="new_country_new"),
    path(
        "new-countries/<slug:source_country_code>/new/",
        views.new_country_new,
        name="new_country_new_for_source",
    ),
    path(
        "new-countries/<slug:source_country_code>/<slug:country_slug>/",
        views.new_country_detail,
        name="new_country_detail",
    ),
    path(
        "new-countries/<slug:source_country_code>/<slug:country_slug>/export-excel/",
        views.new_country_detail_export_excel,
        name="new_country_detail_export_excel",
    ),
    path(
        "new-countries/<slug:country_slug>/export-excel/",
        views.new_country_detail_export_excel_legacy,
        name="new_country_detail_export_excel_legacy",
    ),
    path(
        "new-countries/<slug:country_slug>/",
        views.new_country_detail_legacy,
        name="new_country_detail_legacy",
    ),
    path(
        "new-countries/<slug:source_country_code>/<slug:country_slug>/configs/new/",
        views.new_country_config_new,
        name="new_country_config_new",
    ),
    path(
        "new-countries/<slug:source_country_code>/<slug:country_slug>/configs/new/capital-options/",
        views.new_country_config_capital_options,
        name="new_country_config_capital_options",
    ),
    path(
        "new-countries/<slug:source_country_code>/<slug:country_slug>/configs/new/created-subdivisions/",
        views.new_country_config_created_subdivision_options,
        name="new_country_config_created_subdivision_options",
    ),
    path(
        "new-countries/<slug:source_country_code>/<slug:country_slug>/configs/new/source-areas/",
        views.new_country_config_source_area_options,
        name="new_country_config_source_area_options",
    ),
    path(
        "new-countries/<slug:source_country_code>/<slug:country_slug>/configs/new/created-entities/",
        views.new_country_config_created_entity_options,
        name="new_country_config_created_entity_options",
    ),
    path(
        "new-countries/<slug:country_slug>/configs/new/",
        views.new_country_config_new_legacy,
        name="new_country_config_new_legacy",
    ),
    path(
        "new-countries/<slug:source_country_code>/<slug:country_slug>/configs/<slug:config_slug>/created-entities/",
        views.new_country_config_created_entity_options,
        name="new_country_config_edit_created_entity_options",
    ),
    path(
        "new-countries/<slug:source_country_code>/<slug:country_slug>/configs/<slug:config_slug>/source-areas/",
        views.new_country_config_source_area_options,
        name="new_country_config_edit_source_area_options",
    ),
    path(
        "new-countries/<slug:source_country_code>/<slug:country_slug>/configs/<slug:config_slug>/capital-options/",
        views.new_country_config_capital_options,
        name="new_country_config_edit_capital_options",
    ),
    path(
        "new-countries/<slug:source_country_code>/<slug:country_slug>/configs/<slug:config_slug>/delete/",
        views.new_country_config_delete,
        name="new_country_config_delete",
    ),
    path(
        "new-countries/<slug:source_country_code>/<slug:country_slug>/configs/<slug:config_slug>/clone/",
        views.new_country_config_clone,
        name="new_country_config_clone",
    ),
    path(
        "new-countries/<slug:source_country_code>/<slug:country_slug>/configs/<slug:config_slug>/",
        views.new_country_config_edit,
        name="new_country_config_edit",
    ),
    path(
        "new-countries/<slug:country_slug>/configs/<slug:config_slug>/delete/",
        views.new_country_config_delete_legacy,
        name="new_country_config_delete_legacy",
    ),
    path(
        "new-countries/<slug:country_slug>/configs/<slug:config_slug>/clone/",
        views.new_country_config_clone_legacy,
        name="new_country_config_clone_legacy",
    ),
    path(
        "new-countries/<slug:country_slug>/configs/<slug:config_slug>/",
        views.new_country_config_edit_legacy,
        name="new_country_config_edit_legacy",
    ),
    path(
        "new-countries/<slug:source_country_code>/<slug:country_slug>/configs/<slug:config_slug>/task/<slug:action>/",
        views.start_new_country_config_task,
        name="start_new_country_config_task",
    ),
    path(
        "new-countries/<slug:country_slug>/configs/<slug:config_slug>/task/<slug:action>/",
        views.start_new_country_config_task_legacy,
        name="start_new_country_config_task_legacy",
    ),
    path("groups/", views.group_list, name="group_list"),
    path("groups/import-toml/", views.group_import_toml, name="group_import_toml"),
    path("groups/source-data/", views.group_source_data, name="group_source_data"),
    path("groups/countries/<slug:country_code>/data/", views.group_country_detail_data, name="group_country_detail_data"),
    path("groups/new/", views.group_new, name="group_new"),
    path("groups/groups/<slug:country_code>/new/", views.group_entry_new, name="group_entry_new"),
    path("groups/groups/<slug:country_code>/<slug:group_slug>/", views.group_entry_edit, name="group_entry_edit"),
    path("groups/cities/<slug:country_code>/import-toml/", views.group_city_import_toml, name="group_city_import_toml"),
    path("groups/cities/<slug:country_code>/export-toml/", views.group_city_export_toml, name="group_city_export_toml"),
    path("groups/cities/<slug:country_code>/<slug:city_slug>/", views.group_city_entry, name="group_city_entry"),
    path("groups/subdivisions/<slug:country_code>/new/", views.derived_subdivision_new, name="derived_subdivision_new"),
    path(
        "groups/subdivisions/<slug:country_code>/<slug:subdivision_slug>/data/",
        views.derived_subdivision_form_data,
        name="derived_subdivision_form_data",
    ),
    path(
        "groups/subdivisions/<slug:country_code>/<slug:subdivision_slug>/capital-options/",
        views.derived_subdivision_capital_options,
        name="derived_subdivision_capital_options",
    ),
    path(
        "groups/subdivisions/<slug:country_code>/<slug:subdivision_slug>/delete/",
        views.derived_subdivision_delete,
        name="derived_subdivision_delete",
    ),
    path(
        "groups/subdivisions/<slug:country_code>/<slug:subdivision_slug>/clone/",
        views.derived_subdivision_clone,
        name="derived_subdivision_clone",
    ),
    path(
        "groups/subdivisions/<slug:country_code>/<slug:subdivision_slug>/",
        views.derived_subdivision_edit,
        name="derived_subdivision_edit",
    ),
    path("groups/<slug:slug>/export-toml/", views.group_export_toml, name="group_export_toml"),
    path("groups/<slug:slug>/import-toml/", views.group_import_toml_slug, name="group_import_toml_slug"),
    path("groups/<slug:slug>/", views.group_edit, name="group_edit"),
    path("subdivisions/", views.derived_subdivision_list, name="derived_subdivision_list"),
    path(
        "subdivisions/countries/<slug:country_code>/data/",
        views.derived_subdivision_country_detail_data,
        name="derived_subdivision_country_detail_data",
    ),
    path("subdivisions/import-toml/", views.derived_subdivision_import_toml, name="derived_subdivision_import_toml"),
    path(
        "subdivisions/<slug:slug>/export-toml/",
        views.derived_subdivision_export_toml,
        name="derived_subdivision_export_toml",
    ),
    path(
        "subdivisions/<slug:country_code>/build/",
        views.derived_subdivision_build,
        name="derived_subdivision_build",
    ),
    path("derived/", views.nuevo_area_list, name="nuevo_area_list"),
    path("derived/<slug:country_id>/", views.nuevo_area_detail, name="nuevo_area_detail"),
    path("derived/<slug:country_id>/table/", views.nuevo_area_table, name="nuevo_area_table"),
    path("map/<slug:source>/<path:area_id>/", views.area_map_detail, name="area_map_detail"),
    path(
        "identity/<slug:kind>/entity/<slug:entity_type>/<path:entity_key>/",
        views.visual_identity_entity_detail,
        name="visual_identity_entity_detail",
    ),
    path("identity/<slug:kind>/<path:filename>/", views.visual_identity_detail, name="visual_identity_detail"),
    path("countries/", views.stats_view, name="countries"),
    path("stats/", RedirectView.as_view(pattern_name="ciudades_del_mundo:countries", permanent=False), name="stats"),
    path("stats/data/", views.stats_data, name="stats_data"),
    path("delete/", views.data_delete, name="data_delete"),
    path("tasks/", views.task_list, name="task_list"),
    path("tasks/table/", views.task_table, name="task_table"),
    path("tasks/<slug:task_id>/", views.task_detail, name="task_detail"),
    path("tasks/<slug:task_id>/status/", views.task_status, name="task_status"),
    path("tasks/<slug:task_id>/cancel/", views.task_cancel, name="task_cancel"),
]
