LEGAL_SUBDIVISION = 2

[[pages]]
source = "infosection"
path = ["cities"]
lowest_level = 0

[[pages]]
source = "admin"
path = ["admin"]
lowest_level = 0

[[pages]]
source = "double"
path = [
  "adrar",
  "chlef",
  "laghouat",
  "oumelbouaghi",
  "batna",
  "bejaia",
  "biskra",
  "bechar",
  "blida",
  "bouira",
  "tamanrasset",
  "tebessa",
  "tlemcen",
  "tiaret",
  "tiziouzou",
  "eldjazair",
  "djelfa",
  "jijel",
  "setif",
  "saida",
  "skikda",
  "sidibelabbes",
  "annaba",
  "guelma",
  "constantine",
  "medea",
  "mostaganem",
  "msila",
  "mascara",
  "ouargla",
  "oran",
  "elbayadh",
  "illizi",
  "bordjbouarreridj",
  "boumerdes",
  "eltarf",
  "tindouf",
  "tissemsilt",
  "eloued",
  "khenchela",
  "soukahras",
  "tipaza",
  "mila",
  "aindefla",
  "naama",
  "aintemouchent",
  "ghardaia",
  "relizane",
]
lowest_level = 2
include_tables = ["ts"]
table_levels = { ts = 3 }

[[cities]]
city = "El Djazair"
id = "algr2005"
district_types = ["Commune"]
level = 2
type = "Province Capital"
from = { 1 = ["El Djazair"] }
communes = [
  "El Djazair",
  "Sidi M'Hamed",
  "El Madania",
  "Mohamed Belouizdad (Hamma Annassers)",
  "Bab El Oued",
  "Bologhine",
  "Casbah",
  "Oued Koriche",
  "Bir Mourad Rais",
  "El Biar",
  "El Mouradia",
  "Hydra",
  "Hussein Dey",
  "Kouba",
  "Bachdjerrah",
  "Mohammadia",
  "Bab Ezzouar",
  "Bordj El Kiffan",
  "El Magharia",
  "Bordj El Bahri",
  "El Marsa",
]
