[[pages]]
source = "table"
path = ["cities"]
lowest_level = 0

[[pages]]
source = "admin"
path = ["admin"]
lowest_level = 0

[[cities]]
city = "Oranjestad"
id = "19610"
district_types = ["Urban Area"]
level = 2
type = "City"
from = { 0 = ["244"] }
communes = ["19610"]
keep_communes = false

[[cities]]
city = "Sint Nicolaas"
id = "19611"
district_types = ["Urban Area"]
level = 2
type = "City"
from = { 0 = ["244"] }
communes = ["19611"]
keep_communes = false
