name = "Austria"
country_code = "austria"
LEGAL_SUBDIVISION = 4

[visual_assets.flag]
remote_url = "https://www.citypopulation.de/images/flags/austria.svg"
source = "config"

scrape_schema_version = 2

[[pages]]
source = "admin"
path = ["admin"]
include = { infosection = true, admin1 = true, admin2 = true }

[[pages]]
source = "cities"
path = [
  "burgenland",
  "karnten",
  "niederosterreich",
  "oberosterreich",
  "salzburg",
  "steiermark",
  "tirol",
  "vorarlberg",
  "wien",
]
include = { infosection = true, major_subdivision = true, cities = true }
force_highest_level = 1
include_root = false

[[pages]]
source = "cities"
path = [
  "localities/eisenstadt",
  "localities/gussing",
  "localities/jennersdorf",
  "localities/mattersburg",
  "localities/neusiedl",
  "localities/oberpullendorf",
  "localities/oberwart",
  "localities/feldkirchen",
  "localities/hermagor",
  "localities/klagenfurt",
  "localities/sanktveit",
  "localities/spittal",
  "localities/villach",
  "localities/volkermarkt",
  "localities/wolfsberg",
  "localities/amstetten",
  "localities/baden",
  "localities/bruck",
  "localities/ganserndorf",
  "localities/gmund",
  "localities/hollabrunn",
  "localities/horn",
  "localities/korneuburg",
  "localities/krems",
  "localities/lilienfeld",
  "localities/melk",
  "localities/mistelbach",
  "localities/modling",
  "localities/neunkirchen",
  "localities/sanktpolten",
  "localities/scheibbs",
  "localities/tulln",
  "localities/waidhofen",
  "localities/wienerneustadt",
  "localities/zwettl",
  "localities/braunau",
  "localities/eferding",
  "localities/freistadt",
  "localities/gmunden",
  "localities/grieskirchen",
  "localities/kirchdorf",
  "localities/linz",
  "localities/perg",
  "localities/ried",
  "localities/rohrbach",
  "localities/scharding",
  "localities/steyr",
  "localities/urfahr",
  "localities/vocklabruck",
  "localities/wels",
  "localities/hallein",
  "localities/salzburg",
  "localities/sanktjohann",
  "localities/tamsweg",
  "localities/zellamsee",
  "localities/bruckmurzzuschlag",
  "localities/deutschlandsberg",
  "localities/graz",
  "localities/hartbergfurstenfeld",
  "localities/leibnitz",
  "localities/leoben",
  "localities/liezen",
  "localities/murau",
  "localities/murtal",
  "localities/sudoststeiermark",
  "localities/voitsberg",
  "localities/weiz",
  "localities/imst",
  "localities/innsbruck",
  "localities/kitzbuhel",
  "localities/kufstein",
  "localities/landeck",
  "localities/lienz",
  "localities/reutte",
  "localities/schwaz",
  "localities/bludenz",
  "localities/bregenz",
  "localities/dornbirn",
  "localities/feldkirch",
]
include = { infosection = true, major_subdivision = true, cities = true }
force_highest_level = 2
include_root = false
