LEGAL_SUBDIVISION = 4

[[pages]]
source = "admin"
path = ["admin"]
lowest_level = 0

[[pages]]
source = "table"
path = [
  "localities/eisenstadt",
  "localities/gussing",
  "localities/jennersdorf",
  "localities/mattersburg",
  "localities/neusiedl",
  "localities/oberpullendorf",
  "localities/oberwart",
  "localities/feldkirchen",
  "localities/hermagor",
  "localities/klagenfurt",
  "localities/sanktveit",
  "localities/spittal",
  "localities/villach",
  "localities/volkermarkt",
  "localities/wolfsberg",
  "localities/amstetten",
  "localities/baden",
  "localities/bruck",
  "localities/ganserndorf",
  "localities/gmund",
  "localities/hollabrunn",
  "localities/horn",
  "localities/korneuburg",
  "localities/krems",
  "localities/lilienfeld",
  "localities/melk",
  "localities/mistelbach",
  "localities/modling",
  "localities/neunkirchen",
  "localities/sanktpolten",
  "localities/scheibbs",
  "localities/tulln",
  "localities/waidhofen",
  "localities/wienerneustadt",
  "localities/zwettl",
  "localities/braunau",
  "localities/eferding",
  "localities/freistadt",
  "localities/gmunden",
  "localities/grieskirchen",
  "localities/kirchdorf",
  "localities/linz",
  "localities/perg",
  "localities/ried",
  "localities/rohrbach",
  "localities/scharding",
  "localities/steyr",
  "localities/urfahr",
  "localities/vocklabruck",
  "localities/wels",
  "localities/hallein",
  "localities/salzburg",
  "localities/sanktjohann",
  "localities/tamsweg",
  "localities/zellamsee",
  "localities/bruckmurzzuschlag",
  "localities/deutschlandsberg",
  "localities/graz",
  "localities/hartbergfurstenfeld",
  "localities/leibnitz",
  "localities/leoben",
  "localities/liezen",
  "localities/murau",
  "localities/murtal",
  "localities/sudoststeiermark",
  "localities/voitsberg",
  "localities/weiz",
  "localities/imst",
  "localities/innsbruck",
  "localities/kitzbuhel",
  "localities/kufstein",
  "localities/landeck",
  "localities/lienz",
  "localities/reutte",
  "localities/schwaz",
  "localities/bludenz",
  "localities/bregenz",
  "localities/dornbirn",
  "localities/feldkirch",
]
lowest_level = 3
