[[pages]]
source = "infosection"
path = ["cities"]
lowest_level = 0

[[pages]]
source = "table"
path = [
  "bosanskopodrinjski",
  "brcko",
  "hercegovackoneretvanski",
  "kanton10",
  "posavski",
  "republikasrpska",
  "sarajevo",
  "srednjobosanski",
  "tuzlanski",
  "unskosanski",
  "zapadnohercegovacki",
  "zenickodobojski",
]
lowest_level = 1
