LEGAL_SUBDIVISION = 2

[[pages]]
source = "infosection"
path = ["cities"]
lowest_level = 0

[[pages]]
source = "admin"
path = [
  "regiaonorte/admin",
  "regiaonordeste/admin",
  "regiaocentrooeste/admin",
  "regiaosudeste/admin",
  "regiaosud/admin",
]
lowest_level = 0
