LEGAL_SUBDIVISION = 3

[[pages]]
source = "infosection"
path = ["cities"]
lowest_level = 0

[[pages]]
source = "admin"
path = ["admin"]
lowest_level = 0

[[pages]]
source = "admin"
path = ["distr/admin"]
lowest_level = 1
