[[pages]]
source = "infosection"
path = ["cities"]
lowest_level = 0

[[pages]]
source = "admin"
path = ["admin"]
lowest_level = 0

[[pages]]
source = "table"
path = [
  "bjelovarbilogora",
  "brodposavina",
  "dubrovnikneretva",
  "gradzagreb",
  "istra",
  "karlovac",
  "koprivnicakrizevci",
  "krapinazagorje",
  "likasenj",
  "medimurje",
  "osijekbaranja",
  "pozegaslavonija",
  "primorjegorskikotar",
  "sibenikknin",
  "sisakmoslavina",
  "splitdalmacija",
  "varazdin",
  "viroviticapodravina",
  "vukovarsrijem",
  "zadar",
  "zagreb",
]
lowest_level = 1
include_root = false
include_tables = ["ts"]
table_levels = { tl = 2, ts = 3 }
