LEGAL_SUBDIVISION = 1

[[pages]]
source = "infosection"
path = ["cities"]
lowest_level = 0

[[pages]]
source = "admin"
path = ["admin"]
lowest_level = 0

[[pages]]
source = "table"
path = ["pinardelrio", "artemisa", "lahabana", "mayabeque", "matanzas", "cienfuegos", "villaclara", "sanctispiritus", "ciegodeavila", "camaguey", "lastunas", "holguin", "granma", "santiagodecuba", "guantanamo", "isladelajuventud"]
lowest_level = 1

[visual_assets]
bulk_country_wikidata = true
strict_required = true
required_kinds = ["flag", "coat"]
