name = "Czech Republic"
country_code = "czechrep"
[visual_assets.flag]
remote_url = "https://commons.wikimedia.org/wiki/Special:Redirect/file/Flag%20of%20the%20Czech%20Republic.svg?width=640"
source = "config"

[[pages]]
source = "infosection"
path = ["cities"]
lowest_level = 0

[[pages]]
source = "admin"
path = ["admin"]
lowest_level = 0

[[pages]]
source = "table"
path = [
  "jihoceskykraj",
  "jihomoravskykraj",
  "karlovarskykraj",
  "kralovehradeckykraj",
  "libereckykraj",
  "moravskoslezskykraj",
  "olomouckykraj",
  "pardubickykraj",
  "plzenskykraj",
  "stredoceskykraj",
  "usteckykraj",
  "vysocina",
  "zlinskykraj",
]
lowest_level = 1
include_root = false
include_tables = ["ts"]
table_levels = { tl = 2, ts = 3 }
