LEGAL_SUBDIVISION = 2

[[pages]]
source = "infosection"
path = ["cities"]
lowest_level = 0

[[pages]]
source = "admin"
path = ["admin"]
lowest_level = 0

[[pages]]
source = "admin"
path = ["parish/admin"]
lowest_level = 1
