LEGAL_SUBDIVISION = 4
scrape_schema_version = 2

[[pages]]
source = "cities"
path = ["cities"]
include = { cities = false, infosection = true, major_subdivision = true }

[[pages]]
source = "admin"
path = ["reg/admin"]
include = { infosection = false, major_subdivision = true, minor_subdivision = true }

[[pages]]
source = "admin"
path = ["admin"]
include = { infosection = false, major_subdivision = true, minor_subdivision = true }

[[pages]]
source = "cities"
path = ["ain", "aisne", "allier", "alpesdehauteprovence", "alpesmaritimes", "ardeche", "ardennes", "ariege", "aube", "aude", "aveyron", "basrhin", "bouchesdurhone", "calvados", "cantal", "charente", "charentemaritime", "cher", "correze", "corsedusud", "cotedor", "cotesdarmor", "creuse", "deuxsevres", "dordogne", "doubs", "drome", "essonne", "eure", "eureetloir", "finistere", "gard", "gers", "gironde", "hautecorse", "hautegaronne", "hauteloire", "hautemarne", "hautesalpes", "hautesaone", "hautesavoie", "hautespyrenees", "hautevienne", "hautrhin", "hautsdeseine", "herault", "illeetvilaine", "indre", "indreetloire", "isere", "jura", "landes", "loire", "loireatlantique", "loiret", "loiretcher", "lot", "lotetgaronne", "lozere", "maineetloire", "manche", "marne", "mayenne", "meurtheetmoselle", "meuse", "morbihan", "moselle", "nievre", "nord", "oise", "orne", "pasdecalais", "puydedome", "pyreneesatlantiques", "pyreneesorientales", "rhone", "saoneetloire", "sarthe", "savoie", "seineetmarne", "seinemaritime", "seinesaintdenis", "somme", "tarn", "tarnetgaronne", "territoiredebelfort", "valdemarne", "valdoise", "var", "vaucluse", "vendee", "vienne", "vosges", "yonne", "yvelines"]
include = { cities = true, infosection = false, major_subdivision = true }

[[pages]]
source = "cities"
path = ["paris"]
parent_level = 3
include = { cities = true, infosection = true, major_subdivision = false }

[[pages]]
source = "cities"
path = ["cities/guyane", "cities/guadeloupe", "cities/martinique", "cities/reunion"]
sum_to_root = true
include = { cities = true, infosection = true, major_subdivision = true }
repeat = { infosection = 2 }

[[pages]]
source = "citiesadmin"
path = ["cities/mayotte"]
sum_to_root = true
include = { cities = true, infosection = true, major_subdivision = true, minor_subdivision = true }
repeat = { infosection = 2 }

[visual_assets]
bulk_country_wikidata = true
strict_required = true
required_kinds = ["flag", "coat"]
