LEGAL_SUBDIVISION = 5

[[pages]]
source = "infosection"
path = ["cities"]
lowest_level = 0

[[pages]]
source = "admin"
path = ["reg/admin"]
lowest_level = 0
include_root = false
table_levels = { admin1 = 2, admin2 = 3 }

[[pages]]
source = "admin"
path = ["admin"]
lowest_level = 0
include_root = false
table_levels = { admin1 = 3, admin2 = 4 }

[[pages]]
source = "table"
path = ["ain", "aisne", "allier", "alpesdehauteprovence", "alpesmaritimes", "ardeche", "ardennes", "ariege", "aube", "aude", "aveyron", "basrhin", "bouchesdurhone", "calvados", "cantal", "charente", "charentemaritime", "cher", "correze", "corsedusud", "cotedor", "cotesdarmor", "creuse", "deuxsevres", "dordogne", "doubs", "drome", "essonne", "eure", "eureetloir", "finistere", "gard", "gers", "gironde", "hautecorse", "hautegaronne", "hauteloire", "hautemarne", "hautesalpes", "hautesaone", "hautesavoie", "hautespyrenees", "hautevienne", "hautrhin", "hautsdeseine", "herault", "illeetvilaine", "indre", "indreetloire", "isere", "jura", "landes", "loire", "loireatlantique", "loiret", "loiretcher", "lot", "lotetgaronne", "lozere", "maineetloire", "manche", "marne", "mayenne", "meurtheetmoselle", "meuse", "morbihan", "moselle", "nievre", "nord", "oise", "orne", "paris", "pasdecalais", "puydedome", "pyreneesatlantiques", "pyreneesorientales", "rhone", "saoneetloire", "sarthe", "savoie", "seineetmarne", "seinemaritime", "seinesaintdenis", "somme", "tarn", "tarnetgaronne", "territoiredebelfort", "valdemarne", "valdoise", "var", "vaucluse", "vendee", "vienne", "vosges", "yonne", "yvelines"]
lowest_level = 3
table_levels = { tl = 4, ts = 5 }

[[pages]]
source = "cities"
path = ["cities/guyane"]
lowest_level = 2
table_levels = { tl = 4, ts = 5 }
root_code = "GUF"
root_parent_code = "OVERSEAS"
root_entity_type = "Overseas Department"

[[pages]]
source = "cities"
path = ["cities/guadeloupe"]
lowest_level = 2
table_levels = { tl = 4, ts = 5 }
root_code = "GLP"
root_parent_code = "OVERSEAS"
root_entity_type = "Overseas Department"

[[pages]]
source = "cities"
path = ["cities/martinique"]
lowest_level = 2
table_levels = { tl = 4, ts = 5 }
root_code = "MTQ"
root_parent_code = "OVERSEAS"
root_entity_type = "Overseas Department"

[[pages]]
source = "cities"
path = ["cities/mayotte"]
lowest_level = 2
table_levels = { tl = 4, ts = 5 }
root_code = "MYT"
root_parent_code = "OVERSEAS"
root_entity_type = "Overseas Department"

[[pages]]
source = "cities"
path = ["cities/reunion"]
lowest_level = 2
table_levels = { tl = 4, ts = 5 }
root_code = "REU"
root_parent_code = "OVERSEAS"
root_entity_type = "Overseas Department"

[visual_assets]
bulk_country_wikidata = true
strict_required = true
required_kinds = ["flag", "coat"]
