[[pages]]
source = "infosection"
path = ["cities"]
lowest_level = 0

[[pages]]
source = "admin"
path = ["admin"]
lowest_level = 0

[[pages]]
source = "table"
path = [
  "bacskiskun",
  "baranya",
  "bekes",
  "borsodabaujzemplen",
  "csongrad",
  "fejer",
  "gyormosonsopron",
  "hajdubihar",
  "heves",
  "jasznagykunszolnok",
  "komaromesztergom",
  "nograd",
  "pest",
  "somogy",
  "szabolcsszatmarbereg",
  "tolna",
  "vas",
  "veszprem",
  "zala",
]
lowest_level = 1
include_root = false
include_tables = ["ts"]
table_levels = { tl = 2, ts = 3 }

[[cities]]
city = "Budapest"
id = "01000"
district_types = ["City District"]
level = 2
type = "City"
from = { 1 = ["Budapest"] }
keep_communes = false
