name = "Liechtenstein"
country_code = "liechtenstein"
[visual_assets.flag]
remote_url = "https://www.citypopulation.de/images/flags/liechtenstein.svg"
source = "config"

[[pages]]
source = "table"
path = ["communes"]
lowest_level = 0
