LEGAL_SUBDIVISION = 2

scrape_schema_version = 2

[[pages]]
source = "admin"
path = ["admin"]
include = { infosection = true, admin1 = true, admin2 = true }

[[pages]]
source = "cities"
path = [
  "aguascalientes",
  "bajacalifornia",
  "bajacaliforniasur",
  "campeche",
  "chiapas",
  "chihuahua",
  "ciudaddemexico",
  "coahuila",
  "colima",
  "durango",
  "guanajuato",
  "guerrero",
  "hidalgo",
  "jalisco",
  "mexico/mexico",
  "michoacan",
  "morelos",
  "nayarit",
  "nuevoleon",
  "oaxaca",
  "puebla",
  "queretaro",
  "quintanaroo",
  "sanluispotosi",
  "sinaloa",
  "sonora",
  "tabasco",
  "tamaulipas",
  "tlaxcala",
  "veracruz",
  "yucatan",
  "zacatecas",
]
include = { infosection = true, major_subdivision = true, cities = true }
force_highest_level = 1

[[cities]]
city = "Ciudad de México"
id = "09000"
district_types = ["City District"]
level = 2
type = "City"
from = { 1 = ["Ciudad de México"] }
keep_communes = false
