LEGAL_SUBDIVISION = 3

[[pages]]
source = "infosection"
path = ["cities"]
lowest_level = 0

[[pages]]
source = "admin"
path = ["admin"]
lowest_level = 0

[[pages]]
source = "admin"
path = ["benimellalkhenifra/admin", "draatafilalet/admin", "fesmeknes/admin", "grandcasablancasettat/admin", "guelmimouednoun/admin", "marrakechsafi/admin", "oriental/admin", "rabatsalekenitra/admin", "soussmassa/admin", "tangertetouanalhoceima/admin"]
lowest_level = 1

[[pages]]
source = "table"
path = ["benimellalkhenifra", "draatafilalet", "fesmeknes", "grandcasablancasettat", "guelmimouednoun", "marrakechsafi", "oriental", "rabatsalekenitra", "soussmassa", "tangertetouanalhoceima"]
lowest_level = 2
include_tables = ["ts"]
table_levels = { ts = 4 }

[visual_assets]
bulk_country_wikidata = true
strict_required = true
required_kinds = ["flag", "coat"]
