[[pages]]
source = "admin"
path = ["admin"]
lowest_level = 0

[[pages]]
source = "table"
path = [
  "drenthe",
  "flevoland",
  "friesland",
  "gelderland",
  "groningen",
  "limburg",
  "noordbrabant",
  "noordholland",
  "overijssel",
  "utrecht",
  "zeeland",
  "zuidholland",
]
lowest_level = 1
