LEGAL_SUBDIVISION = 3

scrape_schema_version = 2

[[pages]]
source = "cities"
path = ["cities"]
include = { infosection = true, major_subdivision = false, cities = false }

[[pages]]
source = "admin"
path = ["admin"]
include = { infosection = true, admin1 = true, admin2 = true }

[[pages]]
source = "admin"
path = ["sector/admin"]
include = { infosection = true, admin1 = true, admin2 = true }
force_highest_level = 1
