scrape_schema_version = 2

[[pages]]
source = "cities"
path = ["cities"]
include = { infosection = true, major_subdivision = false, cities = false }

[[pages]]
source = "admin"
path = ["admin"]
include = { infosection = true, admin1 = true, admin2 = true }

[[pages]]
source = "cities"
path = [
  "bor",
  "branicevo",
  "gradbeograd",
  "jablanica",
  "juznabacka",
  "juznibanat",
  "kolubara",
  "macva",
  "moravica",
  "nis",
  "pcinja",
  "pirot",
  "podunavlje",
  "pomoravlje",
  "rasina",
  "raska",
  "severnabacka",
  "severnibanat",
  "srednjibanat",
  "srem",
  "sumadija",
  "toplica",
  "zajecar",
  "zapadnabacka",
  "zlatibor",
]
include = { infosection = true, major_subdivision = true, cities = true }
force_highest_level = 1
include_root = false
