name = "Slovakia"
country_code = "slovakia"
[visual_assets.flag]
remote_url = "https://www.citypopulation.de/images/flags/slovakia.svg"
source = "config"

scrape_schema_version = 2

[[pages]]
source = "cities"
path = ["cities"]
include = { infosection = true, major_subdivision = false, cities = false }

[[pages]]
source = "admin"
path = ["admin"]
include = { infosection = true, admin1 = true, admin2 = true }

[[pages]]
source = "cities"
path = [
  "banskobystrickykraj",
  "bratislavskykraj",
  "kosickykraj",
  "nitrianskykraj",
  "presovskykraj",
  "trencianskykraj",
  "trnavskykraj",
  "zilinskykraj",
]
include = { infosection = true, major_subdivision = true, cities = true }
force_highest_level = 1
include_root = false

[[cities]]
city = "Bratislava"
id = "528000"
district_types = ["City District"]
level = 2
type = "City"
from = { 1 = ["1"] }
keep_communes = true

[[cities]]
city = "Košice"
id = "599000"
district_types = ["City District"]
level = 2
type = "City"
from = { 1 = ["8"] }
keep_communes = true
