[[pages]]
source = "admin"
path = ["admin"]
lowest_level = 0

[[pages]]
source = "table"
path = [
  "gorenjska",
  "goriska",
  "jugovzhodnaslovenija",
  "koroska",
  "obalnokraska",
  "osrednjeslovenska",
  "podravska",
  "pomurska",
  "posavska",
  "primorskonotranjska",
  "savinjska",
  "zasavska",
]
lowest_level = 1
