from ciudades_del_mundo.domain import DivisionSourceType, RepresentationSystem


DIVISIONS = [
    {"type": DivisionSourceType.ADMIN, "urls": "admin", "level": 0},
    {
        "type": DivisionSourceType.TABLE,
        "urls": [
            "andalucia",
            "aragon",
            "asturias",
            "canarias",
            "cantabria",
            "castillalamancha",
            "castillayleon",
            "cataluna",
            "ceuta",
            "comunitatvalenciana",
            "extremadura",
            "galicia",
            "illesbalears",
            "larioja",
            "madrid",
            "melilla",
            "murcia",
            "navarra",
            "paisvasco",
        ],
        "level": 1,
    },
    {
        "type": DivisionSourceType.DOUBLE,
        "urls": [
            "localities/acoruna",
            "localities/alava",
            "localities/albacete",
            "localities/alicante",
            "localities/almeria",
            "localities/asturias",
            "localities/avila",
            "localities/badajoz",
            "localities/barcelona",
            "localities/burgos",
            "localities/caceres",
            "localities/cadiz",
            "localities/cantabria",
            "localities/castellon",
            "localities/ceuta",
            "localities/ciudadreal",
            "localities/cordoba",
            "localities/cuenca",
            "localities/girona",
            "localities/granada",
            "localities/guadalajara",
            "localities/guipuzcoa",
            "localities/huelva",
            "localities/huesca",
            "localities/illesbalears",
            "localities/jaen",
            "localities/larioja",
            "localities/laspalmas",
            "localities/leon",
            "localities/lleida",
            "localities/lugo",
            "localities/madrid",
            "localities/malaga",
            "localities/melilla",
            "localities/murcia",
            "localities/navarra",
            "localities/ourense",
            "localities/palencia",
            "localities/pontevedra",
            "localities/salamanca",
            "localities/santacruzdetenerife",
            "localities/segovia",
            "localities/sevilla",
            "localities/soria",
            "localities/tarragona",
            "localities/teruel",
            "localities/toledo",
            "localities/valencia",
            "localities/valladolid",
            "localities/vizcaya",
            "localities/zamora",
            "localities/zaragoza",
        ],
        "level": 3,
    },
]

LEGAL_SUBDIVISIONS = 3

REPRESENTATION = {
    "level": 2,
    "total": 350,
    "min": 2,
    "min_exceptions": {"spain_51": 1, "spain_52": 1},
    "max_exceptions": {"spain_51": 1, "spain_52": 1},
    "system": RepresentationSystem.DHONDT,
}
