name = "Tunisia"
country_code = "tunisia"
wikidata_id = "Q948"
base_url = "https://www.citypopulation.de/en/"
reset_before_import = true
LEGAL_SUBDIVISION = 3

[[pages]]
source = "admin"
path = ["admin"]
lowest_level = 0

[[pages]]
source = "admin"
path = ["mun/admin"]
lowest_level = 0
