scrape_schema_version = 2

[[pages]]
source = "cities"
path = ["cities"]
include = { infosection = true, major_subdivision = false, cities = false }

[[pages]]
source = "admin"
path = ["admin"]
include = { infosection = true, admin1 = true, admin2 = true }

[[pages]]
source = "cities"
path = [
  "cerkasy",
  "cernihiv",
  "cernivcy",
  "charkiv",
  "cherson",
  "chmelnyckyj",
  "dnipropetrovsk",
  "doneck",
  "ivanofrankivsk",
  "kievcity",
  "kirovohrad",
  "kyiv",
  "luhansk",
  "lviv",
  "mykolaiv",
  "odesa",
  "poltava",
  "rivne",
  "sumy",
  "ternopil",
  "vinnycja",
  "volyn",
  "zakarpattja",
  "zaporizzija",
  "zytomyr",
  "krym",
  "msevastopol",
]
include = { infosection = true, major_subdivision = true, cities = true }
force_highest_level = 1
