# Generated by Django 5.2.1 on 2025-10-18 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminArea',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('country_code', models.CharField(db_index=True, max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField(choices=[(0, 'Country'), (1, 'Admin1 / Región / CCAA'), (2, 'Admin2 / Provincia'), (3, 'Admin3 / Municipio'), (4, 'Admin4'), (5, 'Admin5')])),
                ('area_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('density', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('pop_latest', models.BigIntegerField(blank=True, null=True)),
                ('pop_latest_date', models.DateField(blank=True, null=True)),
                ('last_census_year', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ciudades_del_mundo.adminarea')),
            ],
            options={
                'indexes': [models.Index(fields=['country_code', 'level'], name='ciudades_de_country_b3752d_idx'), models.Index(fields=['level'], name='ciudades_de_level_16f73f_idx'), models.Index(fields=['parent'], name='ciudades_de_parent__20f5df_idx'), models.Index(fields=['name'], name='ciudades_de_name_8b22cb_idx')],
                'constraints': [models.UniqueConstraint(fields=('country_code', 'code'), name='uniq_area_country_code')],
            },
        ),
    ]
