# Generated by Django 5.2.1 on 2025-10-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades_del_mundo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminarea',
            name='entity_type',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddIndex(
            model_name='adminarea',
            index=models.Index(fields=['entity_type'], name='ciudades_de_entity__1475c5_idx'),
        ),
    ]
