# Generated by Django 5.2.1 on 2025-05-17 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades_del_mundo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='country',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='region',
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciudades_del_mundo.country')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ciudades_del_mundo.subdivision')),
            ],
        ),
        migrations.AddField(
            model_name='municipality',
            name='subdivisions',
            field=models.ManyToManyField(to='ciudades_del_mundo.subdivision'),
        ),
    ]
