# Generated by Django 5.2.1 on 2025-05-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades_del_mundo', '0002_country_remove_municipality_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='codeCountry',
            field=models.CharField(default='desconocido', max_length=50),
        ),
    ]
