# Generated by Django 5.2.8 on 2025-11-14 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades_del_mundo', '0002_adminarea_entity_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoAdminArea',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('country_code', models.CharField(db_index=True, max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField(choices=[(0, 'Country'), (1, 'Admin1 / Región / CCAA'), (2, 'Admin2 / Provincia'), (3, 'Admin3 / Municipio'), (4, 'Admin4'), (5, 'Admin5')])),
                ('entity_type', models.CharField(blank=True, max_length=80, null=True)),
                ('area_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('density', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('pop_latest', models.BigIntegerField(blank=True, null=True)),
                ('pop_latest_date', models.DateField(blank=True, null=True)),
                ('last_census_year', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipal_level', models.IntegerField(blank=True, null=True)),
                ('municipios_originales', models.ManyToManyField(blank=True, related_name='nuevo_areas', to='ciudades_del_mundo.adminarea')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ciudades_del_mundo.nuevoadminarea')),
            ],
            options={
                'indexes': [models.Index(fields=['country_code', 'level'], name='ciudades_de_country_1f31e4_idx'), models.Index(fields=['level'], name='ciudades_de_level_9d9484_idx'), models.Index(fields=['parent'], name='ciudades_de_parent__b3e4e8_idx'), models.Index(fields=['name'], name='ciudades_de_name_c97a96_idx'), models.Index(fields=['entity_type'], name='ciudades_de_entity__45f946_idx')],
                'constraints': [models.UniqueConstraint(fields=('country_code', 'code'), name='uniq_nuevo_area_country_code'), models.CheckConstraint(condition=models.Q(('municipal_level__isnull', True), models.Q(('municipal_level__gte', 1), ('municipal_level__lte', 5)), _connector='OR'), name='nuevo_area_municipal_level_valid')],
            },
        ),
    ]
