# Generated by Django 5.2.8 on 2025-11-15 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades_del_mundo', '0003_nuevoadminarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminarea',
            name='capital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_of', to='ciudades_del_mundo.adminarea'),
        ),
        migrations.AddField(
            model_name='adminarea',
            name='most_populate_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='most_populated_of', to='ciudades_del_mundo.adminarea'),
        ),
        migrations.AddField(
            model_name='nuevoadminarea',
            name='capital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_of_new', to='ciudades_del_mundo.adminarea'),
        ),
        migrations.AddField(
            model_name='nuevoadminarea',
            name='most_populate_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='most_populated_of_new', to='ciudades_del_mundo.adminarea'),
        ),
    ]
