# Generated by Django 5.2.1 on 2025-05-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades_del_mundo', '0003_municipality_codecountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='province',
            field=models.CharField(default='desconocido', max_length=50),
        ),
    ]
