# Generated by Django 5.2.8 on 2025-11-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades_del_mundo', '0004_adminarea_capital_adminarea_most_populate_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminarea',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='nuevoadminarea',
            name='capital',
        ),
        migrations.AddField(
            model_name='adminarea',
            name='capitals',
            field=models.ManyToManyField(blank=True, related_name='capital_of', to='ciudades_del_mundo.adminarea'),
        ),
        migrations.AddField(
            model_name='nuevoadminarea',
            name='capitals',
            field=models.ManyToManyField(blank=True, related_name='capital_of_new', to='ciudades_del_mundo.adminarea'),
        ),
    ]
