# Generated by Django 5.2.1 on 2025-05-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades_del_mundo', '0004_municipality_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='size',
            field=models.FloatField(),
        ),
    ]
