# Generated by Django 5.2.8 on 2025-11-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades_del_mundo', '0005_remove_adminarea_capital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.CharField(db_index=True, max_length=128)),
                ('subdivision_id', models.CharField(db_index=True, max_length=128)),
                ('country_code', models.CharField(db_index=True, max_length=64)),
                ('subdivision_code', models.CharField(db_index=True, max_length=64)),
                ('seats', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['country_code', 'subdivision_code'], name='ciudades_de_country_bc3de7_idx'), models.Index(fields=['country_id'], name='ciudades_de_country_06b4ac_idx'), models.Index(fields=['subdivision_id'], name='ciudades_de_subdivi_3a3178_idx')],
                'constraints': [models.UniqueConstraint(fields=('country_code', 'subdivision_code'), name='uniq_escanhos_country_subdivision')],
            },
        ),
    ]
