# Generated by Django 5.2.1 on 2025-05-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades_del_mundo', '0005_alter_municipality_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='type',
            field=models.SmallIntegerField(default=0),
        ),
    ]
