# Generated by Django 5.2.1 on 2025-05-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades_del_mundo', '0006_municipality_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='subdivisions',
        ),
        migrations.AddField(
            model_name='subdivision',
            name='municipalities',
            field=models.ManyToManyField(to='ciudades_del_mundo.municipality'),
        ),
    ]
