# Generated by Django 5.2.8 on 2025-11-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades_del_mundo', '0006_escanho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuevoadminarea',
            name='last_census_year',
        ),
        migrations.RemoveField(
            model_name='nuevoadminarea',
            name='pop_latest_date',
        ),
        migrations.RemoveField(
            model_name='nuevoadminarea',
            name='url',
        ),
    ]
