# Generated by Django 5.2.1 on 2025-05-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades_del_mundo', '0007_remove_municipality_subdivisions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='size',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
