# Generated by Django 5.2.1 on 2025-05-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades_del_mundo', '0008_subdivision_population_subdivision_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdivision',
            name='municipalities',
        ),
    ]
