# Generated by Django 5.2.1 on 2025-05-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades_del_mundo', '0009_remove_subdivision_municipalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='municipalities',
            field=models.ManyToManyField(to='ciudades_del_mundo.municipality'),
        ),
    ]
