# Generated by Django 5.2.1 on 2025-06-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades_del_mundo', '0010_subdivision_municipalities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
