# Generated by Django 5.2.1 on 2025-06-03 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades_del_mundo', '0011_alter_country_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='capital',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='capital_of_subdivision', to='ciudades_del_mundo.municipality'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='mostPopulate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='most_populated_in_subdivision', to='ciudades_del_mundo.municipality'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='municipalities',
            field=models.ManyToManyField(blank=True, related_name='subdivisions', to='ciudades_del_mundo.municipality'),
        ),
    ]
