# Generated by ChatGPT refactor for CityPopulation scraping configuration v2.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ciudades_del_mundo", "0024_adminarea_data_wd"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapingconfig",
            name="schema_version",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="scrapingconfig",
            name="scrape_types",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
