# Generated by ChatGPT explicit parent/repeat config persistence fix.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ciudades_del_mundo", "0025_scrapingconfig_schema_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapingconfig",
            name="pages_config",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
