# Generated by Django 5.2.16 on 2026-07-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades_del_mundo', '0027_derived_country_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedSubdivision',
            fields=[
                ('slug', models.SlugField(max_length=128, primary_key=True, serialize=False)),
                ('internal_name', models.CharField(blank=True, default='', max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('source_country_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('entity_type', models.CharField(blank=True, default='', max_length=80)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source_country_code', 'name', 'slug'],
                'indexes': [models.Index(fields=['source_country_code', 'slug'], name='dersub_source_slug_idx')],
            },
        ),
    ]
